
AllCops:
  TargetRubyVersion: 3.2.0

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  
Style/StringLiteralsInInterpolation:
  Enabled: true
  
Lint/EmptyBlock:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30
