
AllCops:
  TargetRubyVersion: 3.2.0

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Lint/EmptyBlock:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30
